// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -destination=mock_contract_test.go -package=service -source=contract.go
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	"github.com/s21platform/user-service/pkg/user"

	gomock "github.com/golang/mock/gomock"
	model "github.com/s21platform/user-service/internal/model"
	postgres "github.com/s21platform/user-service/internal/repository/postgres"
)

// MockDbRepo is a mock of DbRepo interface.
type MockDbRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDbRepoMockRecorder
	isgomock struct{}
}

// MockDbRepoMockRecorder is the mock recorder for MockDbRepo.
type MockDbRepoMockRecorder struct {
	mock *MockDbRepo
}

// NewMockDbRepo creates a new mock instance.
func NewMockDbRepo(ctrl *gomock.Controller) *MockDbRepo {
	mock := &MockDbRepo{ctrl: ctrl}
	mock.recorder = &MockDbRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDbRepo) EXPECT() *MockDbRepoMockRecorder {
	return m.recorder
}

// CheckFriendship mocks base method.
func (m *MockDbRepo) CheckFriendship(ctx context.Context, peer1, peer2 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckFriendship", ctx, peer1, peer2)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckFriendship indicates an expected call of CheckFriendship.
func (mr *MockDbRepoMockRecorder) CheckFriendship(ctx, peer1, peer2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckFriendship", reflect.TypeOf((*MockDbRepo)(nil).CheckFriendship), ctx, peer1, peer2)
}

// CheckNicknameAvailability mocks base method.
func (m *MockDbRepo) CheckNicknameAvailability(ctx context.Context, nickname string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckNicknameAvailability", ctx, nickname)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckNicknameAvailability indicates an expected call of CheckNicknameAvailability.
func (mr *MockDbRepoMockRecorder) CheckNicknameAvailability(ctx, nickname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckNicknameAvailability", reflect.TypeOf((*MockDbRepo)(nil).CheckNicknameAvailability), ctx, nickname)
}

// CreatePost mocks base method.
func (m *MockDbRepo) CreatePost(ctx context.Context, uuid, content string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePost", ctx, uuid, content)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePost indicates an expected call of CreatePost.
func (mr *MockDbRepoMockRecorder) CreatePost(ctx, uuid, content any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePost", reflect.TypeOf((*MockDbRepo)(nil).CreatePost), ctx, uuid, content)
}

// CreateUser mocks base method.
func (m *MockDbRepo) CreateUser(ctx context.Context, userUUID, email, nickname string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, userUUID, email, nickname)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockDbRepoMockRecorder) CreateUser(ctx, userUUID, email, nickname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockDbRepo)(nil).CreateUser), ctx, userUUID, email, nickname)
}

// GetLoginByUuid mocks base method.
func (m *MockDbRepo) GetLoginByUuid(ctx context.Context, uuid string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoginByUuid", ctx, uuid)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoginByUuid indicates an expected call of GetLoginByUuid.
func (mr *MockDbRepoMockRecorder) GetLoginByUuid(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoginByUuid", reflect.TypeOf((*MockDbRepo)(nil).GetLoginByUuid), ctx, uuid)
}

// GetOrSetUserByLogin mocks base method.
func (m *MockDbRepo) GetOrSetUserByLogin(email string) (*postgres.CheckUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrSetUserByLogin", email)
	ret0, _ := ret[0].(*postgres.CheckUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrSetUserByLogin indicates an expected call of GetOrSetUserByLogin.
func (mr *MockDbRepoMockRecorder) GetOrSetUserByLogin(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrSetUserByLogin", reflect.TypeOf((*MockDbRepo)(nil).GetOrSetUserByLogin), email)
}

// GetPeerFollow mocks base method.
func (m *MockDbRepo) GetPeerFollow(ctx context.Context, userUUID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeerFollow", ctx, userUUID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPeerFollow indicates an expected call of GetPeerFollow.
func (mr *MockDbRepoMockRecorder) GetPeerFollow(ctx, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeerFollow", reflect.TypeOf((*MockDbRepo)(nil).GetPeerFollow), ctx, userUUID)
}

// GetSubscribersCount mocks base method.
func (m *MockDbRepo) GetSubscribersCount(ctx context.Context, userUUID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscribersCount", ctx, userUUID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscribersCount indicates an expected call of GetSubscribersCount.
func (mr *MockDbRepoMockRecorder) GetSubscribersCount(ctx, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscribersCount", reflect.TypeOf((*MockDbRepo)(nil).GetSubscribersCount), ctx, userUUID)
}

// GetSubscriptionCount mocks base method.
func (m *MockDbRepo) GetSubscriptionCount(ctx context.Context, userUUID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionCount", ctx, userUUID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionCount indicates an expected call of GetSubscriptionCount.
func (mr *MockDbRepoMockRecorder) GetSubscriptionCount(ctx, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionCount", reflect.TypeOf((*MockDbRepo)(nil).GetSubscriptionCount), ctx, userUUID)
}

// GetUserForCreation mocks base method.
func (m *MockDbRepo) GetUserForCreation(ctx context.Context, email string) (*model.UserAuthInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserForCreation", ctx, email)
	ret0, _ := ret[0].(*model.UserAuthInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserForCreation indicates an expected call of GetUserForCreation.
func (mr *MockDbRepoMockRecorder) GetUserForCreation(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserForCreation", reflect.TypeOf((*MockDbRepo)(nil).GetUserForCreation), ctx, email)
}

// GetUserInfoByUUID mocks base method.
func (m *MockDbRepo) GetUserInfoByUUID(ctx context.Context, uuid string) (model.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfoByUUID", ctx, uuid)
	ret0, _ := ret[0].(model.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfoByUUID indicates an expected call of GetUserInfoByUUID.
func (mr *MockDbRepoMockRecorder) GetUserInfoByUUID(ctx, uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfoByUUID", reflect.TypeOf((*MockDbRepo)(nil).GetUserInfoByUUID), ctx, uuid)
}

// GetUserWithLimit mocks base method.
func (m *MockDbRepo) GetUserWithLimit(uuid, nickname string, limit, offset int64) ([]model.UserWithLimit, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithLimit", uuid, nickname, limit, offset)
	ret0, _ := ret[0].([]model.UserWithLimit)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUserWithLimit indicates an expected call of GetUserWithLimit.
func (mr *MockDbRepoMockRecorder) GetUserWithLimit(uuid, nickname, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithLimit", reflect.TypeOf((*MockDbRepo)(nil).GetUserWithLimit), uuid, nickname, limit, offset)
}

// GetUsersByUUID mocks base method.
func (m *MockDbRepo) GetUsersByUUID(uuid string) (model.UserInfoMin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByUUID", uuid)
	ret0, _ := ret[0].(model.UserInfoMin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByUUID indicates an expected call of GetUsersByUUID.
func (mr *MockDbRepoMockRecorder) GetUsersByUUID(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByUUID", reflect.TypeOf((*MockDbRepo)(nil).GetUsersByUUID), uuid)
}

// GetWhoFollowPeer mocks base method.
func (m *MockDbRepo) GetWhoFollowPeer(ctx context.Context, userUUID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWhoFollowPeer", ctx, userUUID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWhoFollowPeer indicates an expected call of GetWhoFollowPeer.
func (mr *MockDbRepoMockRecorder) GetWhoFollowPeer(ctx, userUUID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWhoFollowPeer", reflect.TypeOf((*MockDbRepo)(nil).GetWhoFollowPeer), ctx, userUUID)
}

// IsUserExistByUUID mocks base method.
func (m *MockDbRepo) IsUserExistByUUID(uuid string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserExistByUUID", uuid)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsUserExistByUUID indicates an expected call of IsUserExistByUUID.
func (mr *MockDbRepoMockRecorder) IsUserExistByUUID(uuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserExistByUUID", reflect.TypeOf((*MockDbRepo)(nil).IsUserExistByUUID), uuid)
}

// RemoveFriends mocks base method.
func (m *MockDbRepo) RemoveFriends(ctx context.Context, peer1, peer2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFriends", ctx, peer1, peer2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFriends indicates an expected call of RemoveFriends.
func (mr *MockDbRepoMockRecorder) RemoveFriends(ctx, peer1, peer2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFriends", reflect.TypeOf((*MockDbRepo)(nil).RemoveFriends), ctx, peer1, peer2)
}

// SetFriends mocks base method.
func (m *MockDbRepo) SetFriends(ctx context.Context, peer1, peer2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetFriends", ctx, peer1, peer2)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetFriends indicates an expected call of SetFriends.
func (mr *MockDbRepoMockRecorder) SetFriends(ctx, peer1, peer2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFriends", reflect.TypeOf((*MockDbRepo)(nil).SetFriends), ctx, peer1, peer2)
}

// UpdateProfile mocks base method.
func (m *MockDbRepo) UpdateProfile(ctx context.Context, data model.ProfileData, userUuid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, data, userUuid)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockDbRepoMockRecorder) UpdateProfile(ctx, data, userUuid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockDbRepo)(nil).UpdateProfile), ctx, data, userUuid)
}

// MockUserFriendsRegisterSrv is a mock of UserFriendsRegisterSrv interface.
type MockUserFriendsRegisterSrv struct {
	ctrl     *gomock.Controller
	recorder *MockUserFriendsRegisterSrvMockRecorder
	isgomock struct{}
}

// MockUserFriendsRegisterSrvMockRecorder is the mock recorder for MockUserFriendsRegisterSrv.
type MockUserFriendsRegisterSrvMockRecorder struct {
	mock *MockUserFriendsRegisterSrv
}

// NewMockUserFriendsRegisterSrv creates a new mock instance.
func NewMockUserFriendsRegisterSrv(ctrl *gomock.Controller) *MockUserFriendsRegisterSrv {
	mock := &MockUserFriendsRegisterSrv{ctrl: ctrl}
	mock.recorder = &MockUserFriendsRegisterSrvMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserFriendsRegisterSrv) EXPECT() *MockUserFriendsRegisterSrvMockRecorder {
	return m.recorder
}

// ProduceMessage mocks base method.
func (m *MockUserFriendsRegisterSrv) ProduceMessage(ctx context.Context, message, key any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProduceMessage", ctx, message, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProduceMessage indicates an expected call of ProduceMessage.
func (mr *MockUserFriendsRegisterSrvMockRecorder) ProduceMessage(ctx, message, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProduceMessage", reflect.TypeOf((*MockUserFriendsRegisterSrv)(nil).ProduceMessage), ctx, message, key)
}

// MockUserCreatedProducer is a mock of UserCreatedProducer interface.
type MockUserCreatedProducer struct {
	ctrl     *gomock.Controller
	recorder *MockUserCreatedProducerMockRecorder
	isgomock struct{}
}

// MockUserCreatedProducerMockRecorder is the mock recorder for MockUserCreatedProducer.
type MockUserCreatedProducerMockRecorder struct {
	mock *MockUserCreatedProducer
}

// NewMockUserCreatedProducer creates a new mock instance.
func NewMockUserCreatedProducer(ctrl *gomock.Controller) *MockUserCreatedProducer {
	mock := &MockUserCreatedProducer{ctrl: ctrl}
	mock.recorder = &MockUserCreatedProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserCreatedProducer) EXPECT() *MockUserCreatedProducerMockRecorder {
	return m.recorder
}

// ProduceMessage mocks base method.
func (m *MockUserCreatedProducer) ProduceMessage(ctx context.Context, message, key any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProduceMessage", ctx, message, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProduceMessage indicates an expected call of ProduceMessage.
func (mr *MockUserCreatedProducerMockRecorder) ProduceMessage(ctx, message, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProduceMessage", reflect.TypeOf((*MockUserCreatedProducer)(nil).ProduceMessage), ctx, message, key)
}

// MockOptionhubS is a mock of OptionhubS interface.
type MockOptionhubS struct {
	ctrl     *gomock.Controller
	recorder *MockOptionhubSMockRecorder
	isgomock struct{}
}

// MockOptionhubSMockRecorder is the mock recorder for MockOptionhubS.
type MockOptionhubSMockRecorder struct {
	mock *MockOptionhubS
}

// NewMockOptionhubS creates a new mock instance.
func NewMockOptionhubS(ctrl *gomock.Controller) *MockOptionhubS {
	mock := &MockOptionhubS{ctrl: ctrl}
	mock.recorder = &MockOptionhubSMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOptionhubS) EXPECT() *MockOptionhubSMockRecorder {
	return m.recorder
}

// GetOs mocks base method.
func (m *MockOptionhubS) GetOs(ctx context.Context, id *int64) (*model.OS, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOs", ctx, id)
	ret0, _ := ret[0].(*model.OS)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOs indicates an expected call of GetOs.
func (mr *MockOptionhubSMockRecorder) GetOs(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOs", reflect.TypeOf((*MockOptionhubS)(nil).GetOs), ctx, id)
}

// MockUserPostCreatedProduser is a mock of UserPostCreatedProduser interface.
type MockUserPostCreatedProduser struct {
	ctrl     *gomock.Controller
	recorder *MockUserPostCreatedProduserMockRecorder
	isgomock struct{}
}

// MockUserPostCreatedProduserMockRecorder is the mock recorder for MockUserPostCreatedProduser.
type MockUserPostCreatedProduserMockRecorder struct {
	mock *MockUserPostCreatedProduser
}

// NewMockUserPostCreatedProduser creates a new mock instance.
func NewMockUserPostCreatedProduser(ctrl *gomock.Controller) *MockUserPostCreatedProduser {
	mock := &MockUserPostCreatedProduser{ctrl: ctrl}
	mock.recorder = &MockUserPostCreatedProduserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserPostCreatedProduser) EXPECT() *MockUserPostCreatedProduserMockRecorder {
	return m.recorder
}

// ProduceMessage mocks base method.
func (m *MockUserPostCreatedProduser) ProduceMessage(ctx context.Context, message, key any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProduceMessage", ctx, message, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProduceMessage indicates an expected call of ProduceMessage.
func (mr *MockUserPostCreatedProduserMockRecorder) ProduceMessage(ctx, message, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProduceMessage", reflect.TypeOf((*MockUserPostCreatedProduser)(nil).ProduceMessage), ctx, message, key)
}

func (m *MockDbRepo) GetPostsByIds(ctx context.Context, in *user.GetPostsByIdsIn) (*model.PostInfoList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByIds", ctx, in)
	ret0, _ := ret[0].(*model.PostInfoList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}
func (mr *MockDbRepoMockRecorder) GetPostsByIds(ctx context.Context, in *user.GetPostsByIdsIn) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByIds", reflect.TypeOf((*MockDbRepo)(nil).GetPostsByIds), ctx, in)
}
