// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v5.28.1
// source: api/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyFriends struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyFriends) Reset() {
	*x = EmptyFriends{}
	mi := &file_api_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyFriends) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyFriends) ProtoMessage() {}

func (x *EmptyFriends) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyFriends.ProtoReflect.Descriptor instead.
func (*EmptyFriends) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{0}
}

// Data in request or getting uuid by login. If User doesnt exist - user will be creating
type GetUserByLoginIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Email of target user
	Login         string `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByLoginIn) Reset() {
	*x = GetUserByLoginIn{}
	mi := &file_api_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByLoginIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByLoginIn) ProtoMessage() {}

func (x *GetUserByLoginIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByLoginIn.ProtoReflect.Descriptor instead.
func (*GetUserByLoginIn) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserByLoginIn) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

// Message for response
type GetUserByLoginOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID of user
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// Flag for indicate of new user
	IsNewUser     bool `protobuf:"varint,2,opt,name=isNewUser,proto3" json:"isNewUser,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByLoginOut) Reset() {
	*x = GetUserByLoginOut{}
	mi := &file_api_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByLoginOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByLoginOut) ProtoMessage() {}

func (x *GetUserByLoginOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByLoginOut.ProtoReflect.Descriptor instead.
func (*GetUserByLoginOut) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByLoginOut) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *GetUserByLoginOut) GetIsNewUser() bool {
	if x != nil {
		return x.IsNewUser
	}
	return false
}

// Message for request
type IsUserExistByUUIDIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID for target user
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsUserExistByUUIDIn) Reset() {
	*x = IsUserExistByUUIDIn{}
	mi := &file_api_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsUserExistByUUIDIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserExistByUUIDIn) ProtoMessage() {}

func (x *IsUserExistByUUIDIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserExistByUUIDIn.ProtoReflect.Descriptor instead.
func (*IsUserExistByUUIDIn) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{3}
}

func (x *IsUserExistByUUIDIn) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// Message for response
type IsUserExistByUUIDOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Flag of indicate user exist
	IsExist       bool `protobuf:"varint,1,opt,name=isExist,proto3" json:"isExist,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsUserExistByUUIDOut) Reset() {
	*x = IsUserExistByUUIDOut{}
	mi := &file_api_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsUserExistByUUIDOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsUserExistByUUIDOut) ProtoMessage() {}

func (x *IsUserExistByUUIDOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsUserExistByUUIDOut.ProtoReflect.Descriptor instead.
func (*IsUserExistByUUIDOut) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{4}
}

func (x *IsUserExistByUUIDOut) GetIsExist() bool {
	if x != nil {
		return x.IsExist
	}
	return false
}

// Request data fo getting user info (for initiator page)
type GetUserInfoByUUIDIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// UUID for target user
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoByUUIDIn) Reset() {
	*x = GetUserInfoByUUIDIn{}
	mi := &file_api_user_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoByUUIDIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByUUIDIn) ProtoMessage() {}

func (x *GetUserInfoByUUIDIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByUUIDIn.ProtoReflect.Descriptor instead.
func (*GetUserInfoByUUIDIn) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserInfoByUUIDIn) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetOs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOs) Reset() {
	*x = GetOs{}
	mi := &file_api_user_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOs) ProtoMessage() {}

func (x *GetOs) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOs.ProtoReflect.Descriptor instead.
func (*GetOs) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{6}
}

func (x *GetOs) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetOs) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// Response data for initiator page
type GetUserInfoByUUIDOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Surname       *string                `protobuf:"bytes,4,opt,name=surname,proto3,oneof" json:"surname,omitempty"`
	Birthdate     *string                `protobuf:"bytes,5,opt,name=birthdate,proto3,oneof" json:"birthdate,omitempty"`
	Phone         *string                `protobuf:"bytes,6,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	City          *string                `protobuf:"bytes,7,opt,name=city,proto3,oneof" json:"city,omitempty"`
	Telegram      *string                `protobuf:"bytes,8,opt,name=telegram,proto3,oneof" json:"telegram,omitempty"`
	Git           *string                `protobuf:"bytes,9,opt,name=git,proto3,oneof" json:"git,omitempty"`
	Os            *GetOs                 `protobuf:"bytes,10,opt,name=os,proto3,oneof" json:"os,omitempty"`
	Work          *string                `protobuf:"bytes,11,opt,name=work,proto3,oneof" json:"work,omitempty"`
	University    *string                `protobuf:"bytes,12,opt,name=university,proto3,oneof" json:"university,omitempty"`
	Skills        []string               `protobuf:"bytes,13,rep,name=skills,proto3" json:"skills,omitempty"`
	Hobbies       []string               `protobuf:"bytes,14,rep,name=hobbies,proto3" json:"hobbies,omitempty"`
	Uuid          *string                `protobuf:"bytes,15,opt,name=uuid,proto3,oneof" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoByUUIDOut) Reset() {
	*x = GetUserInfoByUUIDOut{}
	mi := &file_api_user_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoByUUIDOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoByUUIDOut) ProtoMessage() {}

func (x *GetUserInfoByUUIDOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoByUUIDOut.ProtoReflect.Descriptor instead.
func (*GetUserInfoByUUIDOut) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserInfoByUUIDOut) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GetUserInfoByUUIDOut) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *GetUserInfoByUUIDOut) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GetUserInfoByUUIDOut) GetSurname() string {
	if x != nil && x.Surname != nil {
		return *x.Surname
	}
	return ""
}

func (x *GetUserInfoByUUIDOut) GetBirthdate() string {
	if x != nil && x.Birthdate != nil {
		return *x.Birthdate
	}
	return ""
}

func (x *GetUserInfoByUUIDOut) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *GetUserInfoByUUIDOut) GetCity() string {
	if x != nil && x.City != nil {
		return *x.City
	}
	return ""
}

func (x *GetUserInfoByUUIDOut) GetTelegram() string {
	if x != nil && x.Telegram != nil {
		return *x.Telegram
	}
	return ""
}

func (x *GetUserInfoByUUIDOut) GetGit() string {
	if x != nil && x.Git != nil {
		return *x.Git
	}
	return ""
}

func (x *GetUserInfoByUUIDOut) GetOs() *GetOs {
	if x != nil {
		return x.Os
	}
	return nil
}

func (x *GetUserInfoByUUIDOut) GetWork() string {
	if x != nil && x.Work != nil {
		return *x.Work
	}
	return ""
}

func (x *GetUserInfoByUUIDOut) GetUniversity() string {
	if x != nil && x.University != nil {
		return *x.University
	}
	return ""
}

func (x *GetUserInfoByUUIDOut) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *GetUserInfoByUUIDOut) GetHobbies() []string {
	if x != nil {
		return x.Hobbies
	}
	return nil
}

func (x *GetUserInfoByUUIDOut) GetUuid() string {
	if x != nil && x.Uuid != nil {
		return *x.Uuid
	}
	return ""
}

type GetLoginByUUIDIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginByUUIDIn) Reset() {
	*x = GetLoginByUUIDIn{}
	mi := &file_api_user_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginByUUIDIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginByUUIDIn) ProtoMessage() {}

func (x *GetLoginByUUIDIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginByUUIDIn.ProtoReflect.Descriptor instead.
func (*GetLoginByUUIDIn) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{8}
}

func (x *GetLoginByUUIDIn) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetLoginByUUIDOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Login         string                 `protobuf:"bytes,1,opt,name=login,proto3" json:"login,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoginByUUIDOut) Reset() {
	*x = GetLoginByUUIDOut{}
	mi := &file_api_user_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoginByUUIDOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoginByUUIDOut) ProtoMessage() {}

func (x *GetLoginByUUIDOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoginByUUIDOut.ProtoReflect.Descriptor instead.
func (*GetLoginByUUIDOut) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{9}
}

func (x *GetLoginByUUIDOut) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

type GetUserWithOffsetIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserWithOffsetIn) Reset() {
	*x = GetUserWithOffsetIn{}
	mi := &file_api_user_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserWithOffsetIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserWithOffsetIn) ProtoMessage() {}

func (x *GetUserWithOffsetIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserWithOffsetIn.ProtoReflect.Descriptor instead.
func (*GetUserWithOffsetIn) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserWithOffsetIn) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserWithOffsetIn) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *GetUserWithOffsetIn) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type GetUserWithOffsetOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          []*User                `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserWithOffsetOut) Reset() {
	*x = GetUserWithOffsetOut{}
	mi := &file_api_user_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserWithOffsetOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserWithOffsetOut) ProtoMessage() {}

func (x *GetUserWithOffsetOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserWithOffsetOut.ProtoReflect.Descriptor instead.
func (*GetUserWithOffsetOut) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserWithOffsetOut) GetUser() []*User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserWithOffsetOut) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetUserWithOffsetOutAll struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	User          []*GetUserInfoByUUIDOut `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	Total         int64                   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserWithOffsetOutAll) Reset() {
	*x = GetUserWithOffsetOutAll{}
	mi := &file_api_user_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserWithOffsetOutAll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserWithOffsetOutAll) ProtoMessage() {}

func (x *GetUserWithOffsetOutAll) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserWithOffsetOutAll.ProtoReflect.Descriptor instead.
func (*GetUserWithOffsetOutAll) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{12}
}

func (x *GetUserWithOffsetOutAll) GetUser() []*GetUserInfoByUUIDOut {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *GetUserWithOffsetOutAll) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Uuid          string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	AvatarLink    string                 `protobuf:"bytes,3,opt,name=avatar_link,json=avatarLink,proto3" json:"avatar_link,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,5,opt,name=surname,proto3" json:"surname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_user_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{13}
}

func (x *User) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *User) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *User) GetAvatarLink() string {
	if x != nil {
		return x.AvatarLink
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

type UpdateProfileIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Birthday      string                 `protobuf:"bytes,2,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Telegram      string                 `protobuf:"bytes,3,opt,name=telegram,proto3" json:"telegram,omitempty"`
	Github        string                 `protobuf:"bytes,4,opt,name=github,proto3" json:"github,omitempty"`
	OsId          int64                  `protobuf:"varint,5,opt,name=os_id,json=osId,proto3" json:"os_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileIn) Reset() {
	*x = UpdateProfileIn{}
	mi := &file_api_user_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileIn) ProtoMessage() {}

func (x *UpdateProfileIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileIn.ProtoReflect.Descriptor instead.
func (*UpdateProfileIn) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateProfileIn) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateProfileIn) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *UpdateProfileIn) GetTelegram() string {
	if x != nil {
		return x.Telegram
	}
	return ""
}

func (x *UpdateProfileIn) GetGithub() string {
	if x != nil {
		return x.Github
	}
	return ""
}

func (x *UpdateProfileIn) GetOsId() int64 {
	if x != nil {
		return x.OsId
	}
	return 0
}

type UpdateProfileOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileOut) Reset() {
	*x = UpdateProfileOut{}
	mi := &file_api_user_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileOut) ProtoMessage() {}

func (x *UpdateProfileOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileOut.ProtoReflect.Descriptor instead.
func (*UpdateProfileOut) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateProfileOut) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// Request message for getting multiple users by their UUIDs
type GetUsersByUUIDIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsersUuid     []*UsersUUID           `protobuf:"bytes,1,rep,name=users_uuid,json=usersUuid,proto3" json:"users_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByUUIDIn) Reset() {
	*x = GetUsersByUUIDIn{}
	mi := &file_api_user_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByUUIDIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByUUIDIn) ProtoMessage() {}

func (x *GetUsersByUUIDIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByUUIDIn.ProtoReflect.Descriptor instead.
func (*GetUsersByUUIDIn) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{16}
}

func (x *GetUsersByUUIDIn) GetUsersUuid() []*UsersUUID {
	if x != nil {
		return x.UsersUuid
	}
	return nil
}

// Response message containing minimal user information
type GetUsersByUUIDOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UsersInfo     []*UserInfoMin         `protobuf:"bytes,1,rep,name=users_info,json=usersInfo,proto3" json:"users_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersByUUIDOut) Reset() {
	*x = GetUsersByUUIDOut{}
	mi := &file_api_user_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersByUUIDOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersByUUIDOut) ProtoMessage() {}

func (x *GetUsersByUUIDOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersByUUIDOut.ProtoReflect.Descriptor instead.
func (*GetUsersByUUIDOut) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{17}
}

func (x *GetUsersByUUIDOut) GetUsersInfo() []*UserInfoMin {
	if x != nil {
		return x.UsersInfo
	}
	return nil
}

// Message for UsersUUID
type UsersUUID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersUUID) Reset() {
	*x = UsersUUID{}
	mi := &file_api_user_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersUUID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersUUID) ProtoMessage() {}

func (x *UsersUUID) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersUUID.ProtoReflect.Descriptor instead.
func (*UsersUUID) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{18}
}

func (x *UsersUUID) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// Min user information structure
type UserInfoMin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Login         string                 `protobuf:"bytes,2,opt,name=login,proto3" json:"login,omitempty"`
	LastAvatar    string                 `protobuf:"bytes,3,opt,name=last_avatar,json=lastAvatar,proto3" json:"last_avatar,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Surname       string                 `protobuf:"bytes,5,opt,name=surname,proto3" json:"surname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfoMin) Reset() {
	*x = UserInfoMin{}
	mi := &file_api_user_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfoMin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfoMin) ProtoMessage() {}

func (x *UserInfoMin) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfoMin.ProtoReflect.Descriptor instead.
func (*UserInfoMin) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{19}
}

func (x *UserInfoMin) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UserInfoMin) GetLogin() string {
	if x != nil {
		return x.Login
	}
	return ""
}

func (x *UserInfoMin) GetLastAvatar() string {
	if x != nil {
		return x.LastAvatar
	}
	return ""
}

func (x *UserInfoMin) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserInfoMin) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

type SetFriendsIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFriendsIn) Reset() {
	*x = SetFriendsIn{}
	mi := &file_api_user_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFriendsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFriendsIn) ProtoMessage() {}

func (x *SetFriendsIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFriendsIn.ProtoReflect.Descriptor instead.
func (*SetFriendsIn) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{20}
}

func (x *SetFriendsIn) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

type SetFriendsOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetFriendsOut) Reset() {
	*x = SetFriendsOut{}
	mi := &file_api_user_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetFriendsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetFriendsOut) ProtoMessage() {}

func (x *SetFriendsOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetFriendsOut.ProtoReflect.Descriptor instead.
func (*SetFriendsOut) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{21}
}

func (x *SetFriendsOut) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveFriendsIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          string                 `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendsIn) Reset() {
	*x = RemoveFriendsIn{}
	mi := &file_api_user_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendsIn) ProtoMessage() {}

func (x *RemoveFriendsIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendsIn.ProtoReflect.Descriptor instead.
func (*RemoveFriendsIn) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{22}
}

func (x *RemoveFriendsIn) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

type RemoveFriendsOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFriendsOut) Reset() {
	*x = RemoveFriendsOut{}
	mi := &file_api_user_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFriendsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendsOut) ProtoMessage() {}

func (x *RemoveFriendsOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendsOut.ProtoReflect.Descriptor instead.
func (*RemoveFriendsOut) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{23}
}

func (x *RemoveFriendsOut) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetCountFriendsOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  int64                  `protobuf:"varint,1,opt,name=subscription,proto3" json:"subscription,omitempty"`
	Subscribers   int64                  `protobuf:"varint,2,opt,name=subscribers,proto3" json:"subscribers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountFriendsOut) Reset() {
	*x = GetCountFriendsOut{}
	mi := &file_api_user_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountFriendsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountFriendsOut) ProtoMessage() {}

func (x *GetCountFriendsOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountFriendsOut.ProtoReflect.Descriptor instead.
func (*GetCountFriendsOut) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{24}
}

func (x *GetCountFriendsOut) GetSubscription() int64 {
	if x != nil {
		return x.Subscription
	}
	return 0
}

func (x *GetCountFriendsOut) GetSubscribers() int64 {
	if x != nil {
		return x.Subscribers
	}
	return 0
}

type Peer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Peer uuid
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Peer) Reset() {
	*x = Peer{}
	mi := &file_api_user_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Peer) ProtoMessage() {}

func (x *Peer) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Peer.ProtoReflect.Descriptor instead.
func (*Peer) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{25}
}

func (x *Peer) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetPeerFollowOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscription  []*Peer                `protobuf:"bytes,1,rep,name=subscription,proto3" json:"subscription,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerFollowOut) Reset() {
	*x = GetPeerFollowOut{}
	mi := &file_api_user_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerFollowOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerFollowOut) ProtoMessage() {}

func (x *GetPeerFollowOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerFollowOut.ProtoReflect.Descriptor instead.
func (*GetPeerFollowOut) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{26}
}

func (x *GetPeerFollowOut) GetSubscription() []*Peer {
	if x != nil {
		return x.Subscription
	}
	return nil
}

// Response subscribers
type GetWhoFollowPeerOut struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Result of the operation
	Subscribers   []*Peer `protobuf:"bytes,1,rep,name=subscribers,proto3" json:"subscribers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWhoFollowPeerOut) Reset() {
	*x = GetWhoFollowPeerOut{}
	mi := &file_api_user_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWhoFollowPeerOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWhoFollowPeerOut) ProtoMessage() {}

func (x *GetWhoFollowPeerOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWhoFollowPeerOut.ProtoReflect.Descriptor instead.
func (*GetWhoFollowPeerOut) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{27}
}

func (x *GetWhoFollowPeerOut) GetSubscribers() []*Peer {
	if x != nil {
		return x.Subscribers
	}
	return nil
}

// Request for subscription
type GetPeerFollowIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Peer uuid
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPeerFollowIn) Reset() {
	*x = GetPeerFollowIn{}
	mi := &file_api_user_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPeerFollowIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeerFollowIn) ProtoMessage() {}

func (x *GetPeerFollowIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeerFollowIn.ProtoReflect.Descriptor instead.
func (*GetPeerFollowIn) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{28}
}

func (x *GetPeerFollowIn) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// Request for subscribers
type GetWhoFollowPeerIn struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Peer uuid
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWhoFollowPeerIn) Reset() {
	*x = GetWhoFollowPeerIn{}
	mi := &file_api_user_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWhoFollowPeerIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWhoFollowPeerIn) ProtoMessage() {}

func (x *GetWhoFollowPeerIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWhoFollowPeerIn.ProtoReflect.Descriptor instead.
func (*GetWhoFollowPeerIn) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{29}
}

func (x *GetWhoFollowPeerIn) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type CheckFriendshipIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFriendshipIn) Reset() {
	*x = CheckFriendshipIn{}
	mi := &file_api_user_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFriendshipIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFriendshipIn) ProtoMessage() {}

func (x *CheckFriendshipIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFriendshipIn.ProtoReflect.Descriptor instead.
func (*CheckFriendshipIn) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{30}
}

func (x *CheckFriendshipIn) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type CheckFriendshipOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Succses       bool                   `protobuf:"varint,1,opt,name=succses,proto3" json:"succses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckFriendshipOut) Reset() {
	*x = CheckFriendshipOut{}
	mi := &file_api_user_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckFriendshipOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckFriendshipOut) ProtoMessage() {}

func (x *CheckFriendshipOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckFriendshipOut.ProtoReflect.Descriptor instead.
func (*CheckFriendshipOut) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{31}
}

func (x *CheckFriendshipOut) GetSuccses() bool {
	if x != nil {
		return x.Succses
	}
	return false
}

type CreateUserIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserIn) Reset() {
	*x = CreateUserIn{}
	mi := &file_api_user_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserIn) ProtoMessage() {}

func (x *CreateUserIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserIn.ProtoReflect.Descriptor instead.
func (*CreateUserIn) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{32}
}

func (x *CreateUserIn) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type CreateUserOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	UserUuid      string                 `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserOut) Reset() {
	*x = CreateUserOut{}
	mi := &file_api_user_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserOut) ProtoMessage() {}

func (x *CreateUserOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserOut.ProtoReflect.Descriptor instead.
func (*CreateUserOut) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{33}
}

func (x *CreateUserOut) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CreateUserOut) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

type CreatePostIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostIn) Reset() {
	*x = CreatePostIn{}
	mi := &file_api_user_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostIn) ProtoMessage() {}

func (x *CreatePostIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostIn.ProtoReflect.Descriptor instead.
func (*CreatePostIn) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{34}
}

func (x *CreatePostIn) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreatePostOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostUuid      string                 `protobuf:"bytes,1,opt,name=post_uuid,json=postUuid,proto3" json:"post_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePostOut) Reset() {
	*x = CreatePostOut{}
	mi := &file_api_user_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePostOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePostOut) ProtoMessage() {}

func (x *CreatePostOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePostOut.ProtoReflect.Descriptor instead.
func (*CreatePostOut) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{35}
}

func (x *CreatePostOut) GetPostUuid() string {
	if x != nil {
		return x.PostUuid
	}
	return ""
}

type UserCreatedMessage struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	UserUuid     string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	UserNickname string                 `protobuf:"bytes,2,opt,name=user_nickname,json=userNickname,proto3" json:"user_nickname,omitempty"`
	// 3 - DEPRECATED (OLD EMAIL)
	RawMessage    []byte `protobuf:"bytes,4,opt,name=raw_message,json=rawMessage,proto3" json:"raw_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCreatedMessage) Reset() {
	*x = UserCreatedMessage{}
	mi := &file_api_user_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCreatedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCreatedMessage) ProtoMessage() {}

func (x *UserCreatedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCreatedMessage.ProtoReflect.Descriptor instead.
func (*UserCreatedMessage) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{36}
}

func (x *UserCreatedMessage) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UserCreatedMessage) GetUserNickname() string {
	if x != nil {
		return x.UserNickname
	}
	return ""
}

func (x *UserCreatedMessage) GetRawMessage() []byte {
	if x != nil {
		return x.RawMessage
	}
	return nil
}

type UserNicknameUpdated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserNicknameUpdated) Reset() {
	*x = UserNicknameUpdated{}
	mi := &file_api_user_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserNicknameUpdated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserNicknameUpdated) ProtoMessage() {}

func (x *UserNicknameUpdated) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserNicknameUpdated.ProtoReflect.Descriptor instead.
func (*UserNicknameUpdated) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{37}
}

func (x *UserNicknameUpdated) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UserNicknameUpdated) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type UserPostCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	PostId        string                 `protobuf:"bytes,2,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserPostCreated) Reset() {
	*x = UserPostCreated{}
	mi := &file_api_user_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserPostCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserPostCreated) ProtoMessage() {}

func (x *UserPostCreated) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserPostCreated.ProtoReflect.Descriptor instead.
func (*UserPostCreated) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{38}
}

func (x *UserPostCreated) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *UserPostCreated) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type PostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostUuid      string                 `protobuf:"bytes,1,opt,name=post_uuid,json=postUuid,proto3" json:"post_uuid,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	AvatarLink    string                 `protobuf:"bytes,4,opt,name=avatar_link,json=avatarLink,proto3" json:"avatar_link,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsEdited      bool                   `protobuf:"varint,7,opt,name=is_edited,json=isEdited,proto3" json:"is_edited,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfo) Reset() {
	*x = PostInfo{}
	mi := &file_api_user_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfo) ProtoMessage() {}

func (x *PostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfo.ProtoReflect.Descriptor instead.
func (*PostInfo) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{39}
}

func (x *PostInfo) GetPostUuid() string {
	if x != nil {
		return x.PostUuid
	}
	return ""
}

func (x *PostInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PostInfo) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *PostInfo) GetAvatarLink() string {
	if x != nil {
		return x.AvatarLink
	}
	return ""
}

func (x *PostInfo) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PostInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *PostInfo) GetIsEdited() bool {
	if x != nil {
		return x.IsEdited
	}
	return false
}

type GetPostsByIdsIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostUuids     []string               `protobuf:"bytes,1,rep,name=post_uuids,json=postUuids,proto3" json:"post_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsByIdsIn) Reset() {
	*x = GetPostsByIdsIn{}
	mi := &file_api_user_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsByIdsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsByIdsIn) ProtoMessage() {}

func (x *GetPostsByIdsIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsByIdsIn.ProtoReflect.Descriptor instead.
func (*GetPostsByIdsIn) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{40}
}

func (x *GetPostsByIdsIn) GetPostUuids() []string {
	if x != nil {
		return x.PostUuids
	}
	return nil
}

type GetPostsByIdsOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*PostInfo            `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsByIdsOut) Reset() {
	*x = GetPostsByIdsOut{}
	mi := &file_api_user_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsByIdsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsByIdsOut) ProtoMessage() {}

func (x *GetPostsByIdsOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_user_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsByIdsOut.ProtoReflect.Descriptor instead.
func (*GetPostsByIdsOut) Descriptor() ([]byte, []int) {
	return file_api_user_proto_rawDescGZIP(), []int{41}
}

func (x *GetPostsByIdsOut) GetPosts() []*PostInfo {
	if x != nil {
		return x.Posts
	}
	return nil
}

var File_api_user_proto protoreflect.FileDescriptor

const file_api_user_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/user.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x0e\n" +
	"\fEmptyFriends\"(\n" +
	"\x10GetUserByLoginIn\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"E\n" +
	"\x11GetUserByLoginOut\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1c\n" +
	"\tisNewUser\x18\x02 \x01(\bR\tisNewUser\")\n" +
	"\x13IsUserExistByUUIDIn\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"0\n" +
	"\x14IsUserExistByUUIDOut\x12\x18\n" +
	"\aisExist\x18\x01 \x01(\bR\aisExist\")\n" +
	"\x13GetUserInfoByUUIDIn\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"-\n" +
	"\x05GetOs\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"\xaa\x04\n" +
	"\x14GetUserInfoByUUIDOut\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\asurname\x18\x04 \x01(\tH\x01R\asurname\x88\x01\x01\x12!\n" +
	"\tbirthdate\x18\x05 \x01(\tH\x02R\tbirthdate\x88\x01\x01\x12\x19\n" +
	"\x05phone\x18\x06 \x01(\tH\x03R\x05phone\x88\x01\x01\x12\x17\n" +
	"\x04city\x18\a \x01(\tH\x04R\x04city\x88\x01\x01\x12\x1f\n" +
	"\btelegram\x18\b \x01(\tH\x05R\btelegram\x88\x01\x01\x12\x15\n" +
	"\x03git\x18\t \x01(\tH\x06R\x03git\x88\x01\x01\x12\x1b\n" +
	"\x02os\x18\n" +
	" \x01(\v2\x06.GetOsH\aR\x02os\x88\x01\x01\x12\x17\n" +
	"\x04work\x18\v \x01(\tH\bR\x04work\x88\x01\x01\x12#\n" +
	"\n" +
	"university\x18\f \x01(\tH\tR\n" +
	"university\x88\x01\x01\x12\x16\n" +
	"\x06skills\x18\r \x03(\tR\x06skills\x12\x18\n" +
	"\ahobbies\x18\x0e \x03(\tR\ahobbies\x12\x17\n" +
	"\x04uuid\x18\x0f \x01(\tH\n" +
	"R\x04uuid\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_surnameB\f\n" +
	"\n" +
	"_birthdateB\b\n" +
	"\x06_phoneB\a\n" +
	"\x05_cityB\v\n" +
	"\t_telegramB\x06\n" +
	"\x04_gitB\x05\n" +
	"\x03_osB\a\n" +
	"\x05_workB\r\n" +
	"\v_universityB\a\n" +
	"\x05_uuid\"&\n" +
	"\x10GetLoginByUUIDIn\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\")\n" +
	"\x11GetLoginByUUIDOut\x12\x14\n" +
	"\x05login\x18\x01 \x01(\tR\x05login\"_\n" +
	"\x13GetUserWithOffsetIn\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\"G\n" +
	"\x14GetUserWithOffsetOut\x12\x19\n" +
	"\x04user\x18\x01 \x03(\v2\x05.UserR\x04user\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"Z\n" +
	"\x17GetUserWithOffsetOutAll\x12)\n" +
	"\x04user\x18\x01 \x03(\v2\x15.GetUserInfoByUUIDOutR\x04user\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x85\x01\n" +
	"\x04User\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x12\n" +
	"\x04uuid\x18\x02 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vavatar_link\x18\x03 \x01(\tR\n" +
	"avatarLink\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x05 \x01(\tR\asurname\"\x8a\x01\n" +
	"\x0fUpdateProfileIn\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\bbirthday\x18\x02 \x01(\tR\bbirthday\x12\x1a\n" +
	"\btelegram\x18\x03 \x01(\tR\btelegram\x12\x16\n" +
	"\x06github\x18\x04 \x01(\tR\x06github\x12\x13\n" +
	"\x05os_id\x18\x05 \x01(\x03R\x04osId\"*\n" +
	"\x10UpdateProfileOut\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"=\n" +
	"\x10GetUsersByUUIDIn\x12)\n" +
	"\n" +
	"users_uuid\x18\x01 \x03(\v2\n" +
	".UsersUUIDR\tusersUuid\"@\n" +
	"\x11GetUsersByUUIDOut\x12+\n" +
	"\n" +
	"users_info\x18\x01 \x03(\v2\f.UserInfoMinR\tusersInfo\"\x1f\n" +
	"\tUsersUUID\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x86\x01\n" +
	"\vUserInfoMin\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x14\n" +
	"\x05login\x18\x02 \x01(\tR\x05login\x12\x1f\n" +
	"\vlast_avatar\x18\x03 \x01(\tR\n" +
	"lastAvatar\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x18\n" +
	"\asurname\x18\x05 \x01(\tR\asurname\"\"\n" +
	"\fSetFriendsIn\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\")\n" +
	"\rSetFriendsOut\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"%\n" +
	"\x0fRemoveFriendsIn\x12\x12\n" +
	"\x04peer\x18\x01 \x01(\tR\x04peer\",\n" +
	"\x10RemoveFriendsOut\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Z\n" +
	"\x12GetCountFriendsOut\x12\"\n" +
	"\fsubscription\x18\x01 \x01(\x03R\fsubscription\x12 \n" +
	"\vsubscribers\x18\x02 \x01(\x03R\vsubscribers\"\x1a\n" +
	"\x04Peer\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"=\n" +
	"\x10GetPeerFollowOut\x12)\n" +
	"\fsubscription\x18\x01 \x03(\v2\x05.PeerR\fsubscription\">\n" +
	"\x13GetWhoFollowPeerOut\x12'\n" +
	"\vsubscribers\x18\x01 \x03(\v2\x05.PeerR\vsubscribers\"%\n" +
	"\x0fGetPeerFollowIn\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"(\n" +
	"\x12GetWhoFollowPeerIn\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"'\n" +
	"\x11CheckFriendshipIn\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\".\n" +
	"\x12CheckFriendshipOut\x12\x18\n" +
	"\asuccses\x18\x01 \x01(\bR\asuccses\"$\n" +
	"\fCreateUserIn\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\"H\n" +
	"\rCreateUserOut\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\"(\n" +
	"\fCreatePostIn\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\",\n" +
	"\rCreatePostOut\x12\x1b\n" +
	"\tpost_uuid\x18\x01 \x01(\tR\bpostUuid\"w\n" +
	"\x12UserCreatedMessage\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12#\n" +
	"\ruser_nickname\x18\x02 \x01(\tR\fuserNickname\x12\x1f\n" +
	"\vraw_message\x18\x04 \x01(\fR\n" +
	"rawMessage\"N\n" +
	"\x13UserNicknameUpdated\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\"G\n" +
	"\x0fUserPostCreated\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x17\n" +
	"\apost_id\x18\x02 \x01(\tR\x06postId\"\xf3\x01\n" +
	"\bPostInfo\x12\x1b\n" +
	"\tpost_uuid\x18\x01 \x01(\tR\bpostUuid\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x1f\n" +
	"\vavatar_link\x18\x04 \x01(\tR\n" +
	"avatarLink\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1b\n" +
	"\tis_edited\x18\a \x01(\bR\bisEdited\"0\n" +
	"\x0fGetPostsByIdsIn\x12\x1d\n" +
	"\n" +
	"post_uuids\x18\x01 \x03(\tR\tpostUuids\"3\n" +
	"\x10GetPostsByIdsOut\x12\x1f\n" +
	"\x05posts\x18\x01 \x03(\v2\t.PostInfoR\x05posts2\xad\a\n" +
	"\vUserService\x129\n" +
	"\x0eGetUserByLogin\x12\x11.GetUserByLoginIn\x1a\x12.GetUserByLoginOut\"\x00\x12B\n" +
	"\x11IsUserExistByUUID\x12\x14.IsUserExistByUUIDIn\x1a\x15.IsUserExistByUUIDOut\"\x00\x12B\n" +
	"\x11GetUserInfoByUUID\x12\x14.GetUserInfoByUUIDIn\x1a\x15.GetUserInfoByUUIDOut\"\x00\x129\n" +
	"\x0eGetLoginByUUID\x12\x11.GetLoginByUUIDIn\x1a\x12.GetLoginByUUIDOut\"\x00\x12B\n" +
	"\x11GetUserWithOffset\x12\x14.GetUserWithOffsetIn\x1a\x15.GetUserWithOffsetOut\"\x00\x126\n" +
	"\rUpdateProfile\x12\x10.UpdateProfileIn\x1a\x11.UpdateProfileOut\"\x00\x129\n" +
	"\x0eGetUsersByUUID\x12\x11.GetUsersByUUIDIn\x1a\x12.GetUsersByUUIDOut\"\x00\x12-\n" +
	"\n" +
	"CreateUser\x12\r.CreateUserIn\x1a\x0e.CreateUserOut\"\x00\x12-\n" +
	"\n" +
	"SetFriends\x12\r.SetFriendsIn\x1a\x0e.SetFriendsOut\"\x00\x126\n" +
	"\rRemoveFriends\x12\x10.RemoveFriendsIn\x1a\x11.RemoveFriendsOut\"\x00\x127\n" +
	"\x0fGetCountFriends\x12\r.EmptyFriends\x1a\x13.GetCountFriendsOut\"\x00\x126\n" +
	"\rGetPeerFollow\x12\x10.GetPeerFollowIn\x1a\x11.GetPeerFollowOut\"\x00\x12?\n" +
	"\x10GetWhoFollowPeer\x12\x13.GetWhoFollowPeerIn\x1a\x14.GetWhoFollowPeerOut\"\x00\x12:\n" +
	"\x0fCheckFriendship\x12\x12.CheckFriendshipIn\x1a\x13.CheckFriendshipOut\x12-\n" +
	"\n" +
	"CreatePost\x12\r.CreatePostIn\x1a\x0e.CreatePostOut\"\x00\x126\n" +
	"\rGetPostsByIds\x12\x10.GetPostsByIdsIn\x1a\x11.GetPostsByIdsOut\"\x00B\n" +
	"Z\bpkg/userb\x06proto3"

var (
	file_api_user_proto_rawDescOnce sync.Once
	file_api_user_proto_rawDescData []byte
)

func file_api_user_proto_rawDescGZIP() []byte {
	file_api_user_proto_rawDescOnce.Do(func() {
		file_api_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_user_proto_rawDesc), len(file_api_user_proto_rawDesc)))
	})
	return file_api_user_proto_rawDescData
}

var file_api_user_proto_msgTypes = make([]protoimpl.MessageInfo, 42)
var file_api_user_proto_goTypes = []any{
	(*EmptyFriends)(nil),            // 0: EmptyFriends
	(*GetUserByLoginIn)(nil),        // 1: GetUserByLoginIn
	(*GetUserByLoginOut)(nil),       // 2: GetUserByLoginOut
	(*IsUserExistByUUIDIn)(nil),     // 3: IsUserExistByUUIDIn
	(*IsUserExistByUUIDOut)(nil),    // 4: IsUserExistByUUIDOut
	(*GetUserInfoByUUIDIn)(nil),     // 5: GetUserInfoByUUIDIn
	(*GetOs)(nil),                   // 6: GetOs
	(*GetUserInfoByUUIDOut)(nil),    // 7: GetUserInfoByUUIDOut
	(*GetLoginByUUIDIn)(nil),        // 8: GetLoginByUUIDIn
	(*GetLoginByUUIDOut)(nil),       // 9: GetLoginByUUIDOut
	(*GetUserWithOffsetIn)(nil),     // 10: GetUserWithOffsetIn
	(*GetUserWithOffsetOut)(nil),    // 11: GetUserWithOffsetOut
	(*GetUserWithOffsetOutAll)(nil), // 12: GetUserWithOffsetOutAll
	(*User)(nil),                    // 13: User
	(*UpdateProfileIn)(nil),         // 14: UpdateProfileIn
	(*UpdateProfileOut)(nil),        // 15: UpdateProfileOut
	(*GetUsersByUUIDIn)(nil),        // 16: GetUsersByUUIDIn
	(*GetUsersByUUIDOut)(nil),       // 17: GetUsersByUUIDOut
	(*UsersUUID)(nil),               // 18: UsersUUID
	(*UserInfoMin)(nil),             // 19: UserInfoMin
	(*SetFriendsIn)(nil),            // 20: SetFriendsIn
	(*SetFriendsOut)(nil),           // 21: SetFriendsOut
	(*RemoveFriendsIn)(nil),         // 22: RemoveFriendsIn
	(*RemoveFriendsOut)(nil),        // 23: RemoveFriendsOut
	(*GetCountFriendsOut)(nil),      // 24: GetCountFriendsOut
	(*Peer)(nil),                    // 25: Peer
	(*GetPeerFollowOut)(nil),        // 26: GetPeerFollowOut
	(*GetWhoFollowPeerOut)(nil),     // 27: GetWhoFollowPeerOut
	(*GetPeerFollowIn)(nil),         // 28: GetPeerFollowIn
	(*GetWhoFollowPeerIn)(nil),      // 29: GetWhoFollowPeerIn
	(*CheckFriendshipIn)(nil),       // 30: CheckFriendshipIn
	(*CheckFriendshipOut)(nil),      // 31: CheckFriendshipOut
	(*CreateUserIn)(nil),            // 32: CreateUserIn
	(*CreateUserOut)(nil),           // 33: CreateUserOut
	(*CreatePostIn)(nil),            // 34: CreatePostIn
	(*CreatePostOut)(nil),           // 35: CreatePostOut
	(*UserCreatedMessage)(nil),      // 36: UserCreatedMessage
	(*UserNicknameUpdated)(nil),     // 37: UserNicknameUpdated
	(*UserPostCreated)(nil),         // 38: UserPostCreated
	(*PostInfo)(nil),                // 39: PostInfo
	(*GetPostsByIdsIn)(nil),         // 40: GetPostsByIdsIn
	(*GetPostsByIdsOut)(nil),        // 41: GetPostsByIdsOut
	(*timestamppb.Timestamp)(nil),   // 42: google.protobuf.Timestamp
}
var file_api_user_proto_depIdxs = []int32{
	6,  // 0: GetUserInfoByUUIDOut.os:type_name -> GetOs
	13, // 1: GetUserWithOffsetOut.user:type_name -> User
	7,  // 2: GetUserWithOffsetOutAll.user:type_name -> GetUserInfoByUUIDOut
	18, // 3: GetUsersByUUIDIn.users_uuid:type_name -> UsersUUID
	19, // 4: GetUsersByUUIDOut.users_info:type_name -> UserInfoMin
	25, // 5: GetPeerFollowOut.subscription:type_name -> Peer
	25, // 6: GetWhoFollowPeerOut.subscribers:type_name -> Peer
	42, // 7: PostInfo.created_at:type_name -> google.protobuf.Timestamp
	39, // 8: GetPostsByIdsOut.posts:type_name -> PostInfo
	1,  // 9: UserService.GetUserByLogin:input_type -> GetUserByLoginIn
	3,  // 10: UserService.IsUserExistByUUID:input_type -> IsUserExistByUUIDIn
	5,  // 11: UserService.GetUserInfoByUUID:input_type -> GetUserInfoByUUIDIn
	8,  // 12: UserService.GetLoginByUUID:input_type -> GetLoginByUUIDIn
	10, // 13: UserService.GetUserWithOffset:input_type -> GetUserWithOffsetIn
	14, // 14: UserService.UpdateProfile:input_type -> UpdateProfileIn
	16, // 15: UserService.GetUsersByUUID:input_type -> GetUsersByUUIDIn
	32, // 16: UserService.CreateUser:input_type -> CreateUserIn
	20, // 17: UserService.SetFriends:input_type -> SetFriendsIn
	22, // 18: UserService.RemoveFriends:input_type -> RemoveFriendsIn
	0,  // 19: UserService.GetCountFriends:input_type -> EmptyFriends
	28, // 20: UserService.GetPeerFollow:input_type -> GetPeerFollowIn
	29, // 21: UserService.GetWhoFollowPeer:input_type -> GetWhoFollowPeerIn
	30, // 22: UserService.CheckFriendship:input_type -> CheckFriendshipIn
	34, // 23: UserService.CreatePost:input_type -> CreatePostIn
	40, // 24: UserService.GetPostsByIds:input_type -> GetPostsByIdsIn
	2,  // 25: UserService.GetUserByLogin:output_type -> GetUserByLoginOut
	4,  // 26: UserService.IsUserExistByUUID:output_type -> IsUserExistByUUIDOut
	7,  // 27: UserService.GetUserInfoByUUID:output_type -> GetUserInfoByUUIDOut
	9,  // 28: UserService.GetLoginByUUID:output_type -> GetLoginByUUIDOut
	11, // 29: UserService.GetUserWithOffset:output_type -> GetUserWithOffsetOut
	15, // 30: UserService.UpdateProfile:output_type -> UpdateProfileOut
	17, // 31: UserService.GetUsersByUUID:output_type -> GetUsersByUUIDOut
	33, // 32: UserService.CreateUser:output_type -> CreateUserOut
	21, // 33: UserService.SetFriends:output_type -> SetFriendsOut
	23, // 34: UserService.RemoveFriends:output_type -> RemoveFriendsOut
	24, // 35: UserService.GetCountFriends:output_type -> GetCountFriendsOut
	26, // 36: UserService.GetPeerFollow:output_type -> GetPeerFollowOut
	27, // 37: UserService.GetWhoFollowPeer:output_type -> GetWhoFollowPeerOut
	31, // 38: UserService.CheckFriendship:output_type -> CheckFriendshipOut
	35, // 39: UserService.CreatePost:output_type -> CreatePostOut
	41, // 40: UserService.GetPostsByIds:output_type -> GetPostsByIdsOut
	25, // [25:41] is the sub-list for method output_type
	9,  // [9:25] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_user_proto_init() }
func file_api_user_proto_init() {
	if File_api_user_proto != nil {
		return
	}
	file_api_user_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_user_proto_rawDesc), len(file_api_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   42,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_user_proto_goTypes,
		DependencyIndexes: file_api_user_proto_depIdxs,
		MessageInfos:      file_api_user_proto_msgTypes,
	}.Build()
	File_api_user_proto = out.File
	file_api_user_proto_goTypes = nil
	file_api_user_proto_depIdxs = nil
}
