openapi: 3.0.3
info:
  title: User Service
  version: 1.0.0

paths:
  /api/user/me/personality:
    get:
      summary: Ручка для получения данных для своей странички
      operationId: MyPersonality
      parameters:
        - name: X-User-Uuid
          in: header
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyPersonality'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        500:
          $ref: '#/components/responses/InternalError'

  /api/user/attributes:
    get:
      summary: Ручка для получения атрибутов пользователя по их ID
      operationId: GetUserAttributes
      parameters:
        - name: X-User-Uuid
          in: header
          required: true
          schema:
            type: string
        - name: attribute_ids
          in: query
          required: true
          schema:
            type: array
            items:
              type: integer
              format: int64
          style: form
          explode: false
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAttributesResponse'
        400:
          $ref: '#/components/responses/BadRequest'
        401:
          $ref: '#/components/responses/Unauthorized'
        403:
          $ref: '#/components/responses/Forbidden'
        500:
          $ref: '#/components/responses/InternalError'

components:
  schemas:
    MyPersonality:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/ProfileItem'
    ProfileItem:
      type: object
      required:
        - title
        - type
      properties:
        title:
          type: string
        type:
          type: string
        value:
          type: string
        enum_values:
          type: array
          items:
            type: string

    UserAttributesResponse:
      type: object
      required:
        - data
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/AttributeItem'
    AttributeItem:
      type: object
      required:
        - title
        - attribute_id
        - type
      properties:
        title:
          type: string
        attribute_id:
          type: integer
          format: int64
        type:
          type: string
        value_string:
          type: string
        value_int:
          type: integer
          format: int64
        value_date:
          type: string
          format: date
    Error:
      type: object
      properties:
        message:
          type: string
      required:
        - message

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    InternalError:
      description: Internal Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: Resource is not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
